# Defenders

### Random Forest

```{r}

# Creating a table to remove all the factor variables with more than 40 factors
# Filtering out positions 2 - 6 

# All Variables

Defenders2 <- Defenders1 %>% 
    select(-region, -PlayerYearComp_id, -Url, -Season_End_Year, -Squad, 
           -Player, -Nation, -Pos, -Age, -Born, -player_dob, -player_name, 
           -player_num, -squad, -country, -comp_name, -player_nationality, 
           -current_club, -player_height_mtrs, -date_joined, -joined_from, 
           -contract_expiry, -player_url) %>% 
    filter(player_position == 'Right-Back' | player_position == 'Left-Back'| 
           player_position == 'Centre-Back' | player_position == 'Defensive Midfield')

RF_AllVariables <- randomForest(player_market_value_euro ~ .,
                       data = Defenders2,
                       type = regression,
                       mtry = 4,
                       na.action = na.roughfix,
                       ntree = 1500)
print(RF_AllVariables)
plot(RF_AllVariables)

# Let's look at the Defense table only 
defenseOnly <- inner_join(x = defense,
                             y = market_values,
                             by = "PlayerYearComp_id",
                             suffix = c("",".REMOVEDUPLICATE"))

defenseOnly <- defenseOnly %>% select(-contains("REMOVEDUPLICATE"))


defenseOnly1 <- defenseOnly %>% 
  select(-Season_End_Year, -Squad, -Player, -Nation, -Pos, -Age, -Born, -Url, 
         -PlayerYearComp_id, -region, -player_dob, -player_name, 
           -player_num, -squad, -country, -comp_name, -player_nationality, 
           -current_club, -player_height_mtrs, -date_joined, -joined_from, 
           -contract_expiry, -player_url) %>% 
    filter(player_position == 'Right-Back' | player_position == 'Left-Back'| 
           player_position == 'Centre-Back' | player_position == 'Defensive Midfield')

RF_DefenseVariables <- randomForest(player_market_value_euro ~ .,
                       data = defenseOnly1,
                       type = regression,
                       mtry = 3,
                       na.action = na.roughfix,
                       ntree = 1500)

print(RF_DefenseVariables)
plot(RF_DefenseVariables)
```

```{r}
# All Variables
rf_mods <- list()
oob_err <- NULL
test_err <- NULL
for(mtry in 1:9){
  rf_fit_all <- randomForest(player_market_value_euro ~ 
                           ., 
                         data = Defenders2,
                         mtry = mtry,
                         na.action = na.roughfix,
                         ntree = 600)
  oob_err[mtry] <- rf_fit_all$mse[600]
  
  cat(mtry," ")
}
## 1  2  3  4  5  6  7  8  9
results_DF <- data.frame(mtry = 1:9, oob_err)
ggplot(results_DF, aes(x = mtry, y = oob_err)) + geom_point() + theme_minimal() + xlim(1,9)

# Defense
rf_mods <- list()
oob_err <- NULL
test_err <- NULL
for(mtry in 1:9){
  rf_fit_defense <- randomForest(player_market_value_euro ~ 
                           ., 
                         data = defenseOnly1,
                         mtry = mtry,
                         na.action = na.roughfix,
                         ntree = 600)
  oob_err[mtry] <- rf_fit_defense$mse[600]
  
  cat(mtry," ")
}
## 1  2  3  4  5  6  7  8  9
results_DF <- data.frame(mtry = 1:9, oob_err)
ggplot(results_DF, aes(x = mtry, y = oob_err)) + geom_point() + theme_minimal() + xlim(1,9)
```

```{r}
varImpPlot(rf_fit_all, n.var = 15)

varImpPlot(rf_fit_defense, n.var = 15)

```

**Important Variables**

`W`: Wins

`onG`: Goals scored by team while on pitch

`xG +/-` : Expected Goals Scored minus Expected Goals Allowed

`CS`: Clean Ssheets

`+/-`: Goals Scored minus Goals Allowed

### Linear Regression

```{r}
Defenders_LinReg <- lm(player_market_value_euro ~ onG + CS + xGplus_per_minus,
                         data = Goalkeepers2)

summary(Defenders_LinReg)
```

We have an adjusted R square of .46 with coefficients


